<?php
return array (
  13 => 
  array (
    'id' => '13',
    'catid' => '15',
    'typeid' => '0',
    'title' => '一带一路1一带一路1',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042501301.jpg',
    'keywords' => '一带',
    'description' => '一带一路1一带一路1一带一路1一带一路1',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=15&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529742285',
    'updatetime' => '1529742306',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '15',
    'typeid' => '0',
    'title' => '一带一路2一带一路2一带一路2',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042529414.jpg',
    'keywords' => '一带',
    'description' => '一带一路2一带一路2一带一路2一带一路2一带一路2一带一路2',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=15&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529742309',
    'updatetime' => '1529742333',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  30 => 
  array (
    'id' => '30',
    'catid' => '15',
    'typeid' => '0',
    'title' => '一带一路3一带一路3一带一路3一带一路3',
    'style' => '',
    'thumb' => '',
    'keywords' => '一带',
    'description' => '一带一路3一带一路3一带一路3一带一路3一带一路3一带一路3一带一路3一带一路3一带一路3一带一路3一带一路3一带一路3',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=15&id=30',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529806123',
    'updatetime' => '1529806138',
    'hitsid' => 'c-1-30',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  31 => 
  array (
    'id' => '31',
    'catid' => '15',
    'typeid' => '0',
    'title' => '一带一路4',
    'style' => '',
    'thumb' => '',
    'keywords' => '一带',
    'description' => '一带一路4一带一路4一带一路4一带一路4一带一路4',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=15&id=31',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529806140',
    'updatetime' => '1529806152',
    'hitsid' => 'c-1-31',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '15',
    'typeid' => '0',
    'title' => '一带一路5',
    'style' => '',
    'thumb' => '',
    'keywords' => '一带',
    'description' => '一带一路5一带一路5一带一路5一带一路5一带一路5一带一路5一带一路5',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=15&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529806154',
    'updatetime' => '1529806167',
    'hitsid' => 'c-1-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>