<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '10',
    'typeid' => '0',
    'title' => '行业资讯1行业资讯1',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042014928.jpg',
    'keywords' => '行业 资讯',
    'description' => '行业资讯1行业资讯1行业资讯1行业资讯1行业资讯1',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=10&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529741993',
    'updatetime' => '1529742020',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '10',
    'typeid' => '0',
    'title' => '行业资讯2行业资讯2',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042044300.jpg',
    'keywords' => '行业 资讯',
    'description' => '行业资讯2行业资讯2行业资讯2行业资讯2行业资讯2行业资讯2行业资讯2行业资讯2',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=10&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529742024',
    'updatetime' => '1529742049',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>