<?php
return array (
  72 => 
  array (
    'id' => '72',
    'catid' => '21',
    'typeid' => '0',
    'title' => '重庆九宫格火锅 激情四射',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704032908500.gif',
    'keywords' => '重',
    'description' => '据说重庆六家餐馆里有五家都是火锅店。不论是端午节、元宵节还是春节，总是少不了涮桌火锅的惯例。重庆火锅的特色就是热情似火、麻辣过瘾。   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=72',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530689305',
    'updatetime' => '1531908022',
    'hitsid' => 'c-1-72',
    'views' => '7',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '7',
  ),
  62 => 
  array (
    'id' => '62',
    'catid' => '21',
    'typeid' => '0',
    'title' => '不吹不黑，中国最好吃的牛肉在哪里',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704025038957.jpg',
    'keywords' => '最好吃，牛肉',
    'description' => '随着收入不断提高，牛肉如今已经成为很多中国人饭桌上的不可或缺的菜肴，从家常烹饪到煎烤牛排，再到牛肉干等小吃都深受人们喜爱。以口味清淡、肉质新鲜为主要特色的潮汕火锅',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=62',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530686388',
    'updatetime' => '1530687984',
    'hitsid' => 'c-1-62',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  71 => 
  array (
    'id' => '71',
    'catid' => '21',
    'typeid' => '0',
    'title' => '韩国首尔广藏市场很有料',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704032814370.jpg',
    'keywords' => '首尔',
    'description' => '随着城市的不断发展，各类传统市场逐渐失去了空间而被拆除，例如北京的崇文门市场等等，都有不短的历史。这类市场其实早已经超越了单纯的商   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=71',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530689251',
    'updatetime' => '1530689800',
    'hitsid' => 'c-1-71',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  63 => 
  array (
    'id' => '63',
    'catid' => '21',
    'typeid' => '0',
    'title' => '迎接上海的梅雨季，除了红豆饭，还有油辣椒',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704030959163.jpg',
    'keywords' => '油辣椒',
    'description' => '这是我来上海的第9天，7、8号两天艳阳高照，在窗外晒出来的衣服都是香香的味道；但是，这样的天气不能常有，这几天上海进入了阴天&mdash;&mdash;没有   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=63',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530688103',
    'updatetime' => '1530688236',
    'hitsid' => 'c-1-63',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  67 => 
  array (
    'id' => '67',
    'catid' => '21',
    'typeid' => '0',
    'title' => '游记丨你吃过和没吃过的武汉',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704032220102.jpg',
    'keywords' => '武汉',
    'description' => '为什么会有这趟说走就走的又一次独自旅行，要知道野猪为了寻找食物，可以跑三十多公里的路。七八百公里的距离高铁也是嗖地一下到了。下面就   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=67',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530688844',
    'updatetime' => '1530688955',
    'hitsid' => 'c-1-67',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  64 => 
  array (
    'id' => '64',
    'catid' => '21',
    'typeid' => '0',
    'title' => '越吃越水嫩，神奇小番茄帮你完成逆生长！',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704031234180.jpg',
    'keywords' => '小番茄',
    'description' => '今天为大家带来一道神奇小番茄。这道加了料的小番茄，有颜值有内涵，但最特别的是，它是烤制而成的。如果说要把番茄做熟，每个人都能举出一   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=64',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530688261',
    'updatetime' => '1530688363',
    'hitsid' => 'c-1-64',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  65 => 
  array (
    'id' => '65',
    'catid' => '21',
    'typeid' => '0',
    'title' => '北京人：麻酱就是我的命',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704031543910.jpg',
    'keywords' => '麻将',
    'description' => '每一个北京人，都是麻酱控。从发音上，你就能听出他们对芝麻酱的爱是发自内心的、深入骨髓的、至高无上的、绝非那些街边小吃可以比的。就像   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=65',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530688383',
    'updatetime' => '1530688553',
    'hitsid' => 'c-1-65',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  66 => 
  array (
    'id' => '66',
    'catid' => '21',
    'typeid' => '0',
    'title' => '香嫩幼滑的杏仁玉露膏，温润又滋补！',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0704/20180704031948228.jpg',
    'keywords' => '豆腐',
    'description' => '杏仁豆腐是夏天我最爱的小甜点。嫩白光洁的豆腐小块，浮在清澈的糖水上面，桂花则散落在碗底。看着小碗里的杏仁豆腐，无论头顶着炎炎烈日，   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=21&id=66',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530688566',
    'updatetime' => '1530688716',
    'hitsid' => 'c-1-66',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>