<?php
return array (
  34 => 
  array (
    'id' => '34',
    'catid' => '6',
    'typeid' => '0',
    'title' => '央行年内第三次降准：有何不同？传递哪些政策信号',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '中新网客户端北京6月25日电 (记者 程春雨)央行24日宣布年内第三次定向降准。7月5日起，下调国有大型商业银行等人民币存款准备金率0 5个百   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=34',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914396',
    'updatetime' => '1531964229',
    'hitsid' => 'c-1-34',
    'views' => '23',
    'yesterdayviews' => '0',
    'dayviews' => '23',
    'weekviews' => '23',
    'monthviews' => '23',
  ),
  38 => 
  array (
    'id' => '38',
    'catid' => '6',
    'typeid' => '0',
    'title' => '井柏然倪妮疑似分手：换掉情侣头像，活动全程无交流',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '井柏然和倪妮的恋情自曝光以来就饱受关注，虽然小情侣私底下挺低调，但也时不时地让网友们吃一波狗粮，比如被网友拍到穿情侣装逛商场，互相   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=38',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914495',
    'updatetime' => '1531964359',
    'hitsid' => 'c-1-38',
    'views' => '2',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  43 => 
  array (
    'id' => '43',
    'catid' => '6',
    'typeid' => '0',
    'title' => '世界杯第12日看点：小组赛末轮开战 伊朗恶斗葡萄牙',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '腾讯体育6月25日讯 2018年俄罗斯世界杯进入第12个比赛日，小组赛第三轮将全面打响。同之前的比赛日不同，每日将有四场比赛进行。今晚22时   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=43',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914623',
    'updatetime' => '1531964559',
    'hitsid' => 'c-1-43',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  42 => 
  array (
    'id' => '42',
    'catid' => '6',
    'typeid' => '0',
    'title' => '王祖蓝为开车超速道歉：一时心急，给大家做了反面教材',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '我们都知道开车上路，安全第一，今天中午王祖蓝发博回应了前几天开快车，他的微博配文前几天一时心急开了快车，给大家做了反面教材，希望大   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=42',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914606',
    'updatetime' => '1531908348',
    'hitsid' => 'c-1-42',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '头条新闻111',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623035844594.jpeg',
    'keywords' => '',
    'description' => '头条新闻111头条新闻111头条新闻111头条新闻111头条新闻111头条新闻111头条新闻111头条新闻111头条新闻111头条新',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529740607',
    'updatetime' => '1529741851',
    'hitsid' => 'c-1-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '头条新闻222',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623041800986.jpeg',
    'keywords' => '新闻',
    'description' => '头条新闻222头条新闻222头条新闻222头条新闻222',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529741856',
    'updatetime' => '1529829735',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '6',
    'typeid' => '0',
    'title' => '美国国防部长马蒂斯将于6月26日至28日访问中国',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '记者：据报道，美国防长马蒂斯近日对记者称，他将于近期先后访问中国和韩国。请问能否证实？如属实，中方哪些官员将与马蒂斯会晤？双方将谈   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=33',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914368',
    'updatetime' => '1529914384',
    'hitsid' => 'c-1-33',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  35 => 
  array (
    'id' => '35',
    'catid' => '6',
    'typeid' => '0',
    'title' => '中国海警船今巡航钓鱼岛领海 日本外务省抗议',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '【环球网 记者 屈腾飞】6月25日上午，中国海警船编队进入钓鱼岛领海巡航。日本外务省官员当天向中国大使馆表示抗议，日本政府还将首相官   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=35',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914422',
    'updatetime' => '1529914433',
    'hitsid' => 'c-1-35',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  36 => 
  array (
    'id' => '36',
    'catid' => '6',
    'typeid' => '0',
    'title' => '云南孟连公安局纪委书记用自己交换人质 当场脱下防刺背心',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '此行到云南是为了采访边境线上的纪检监察干部，途中，听说在中缅交界的孟连县，曾任县公安局纪委书记的李文宏不简单，是个有故事的人，遂绕   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=36',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914445',
    'updatetime' => '1529914456',
    'hitsid' => 'c-1-36',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  37 => 
  array (
    'id' => '37',
    'catid' => '6',
    'typeid' => '0',
    'title' => '全国首例！西安暂停企事业单位买住房，有何考虑',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '中新网客户端北京6月25日电 (记者 邱宇)西安近日发布楼市新政，限购区域内，暂停向企事业单位及其他机构销售住房。业内专家分析称，此乃   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=6&id=37',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529914465',
    'updatetime' => '1529914475',
    'hitsid' => 'c-1-37',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>