<?php
return array (
  73 => 
  array (
    'id' => '73',
    'catid' => '24',
    'typeid' => '0',
    'title' => '子栏目1文章1',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0706/20180706100231578.jpg',
    'keywords' => '',
    'description' => '子栏目1文章1子栏目1文章1子栏目1文章1子栏目1文章1子栏目1文章1子栏目1文章1子栏目1文章1子栏目1文章1子栏目1文章1',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=24&id=73',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530842502',
    'updatetime' => '1530842566',
    'hitsid' => 'c-1-73',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '24',
    'typeid' => '0',
    'title' => '子栏目12',
    'style' => '',
    'thumb' => '',
    'keywords' => '子栏目12',
    'description' => '子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子栏目12子   ',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=24&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1531743044',
    'updatetime' => '1531743061',
    'hitsid' => 'c-1-79',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  80 => 
  array (
    'id' => '80',
    'catid' => '24',
    'typeid' => '0',
    'title' => '子栏目13',
    'style' => '',
    'thumb' => '',
    'keywords' => '栏目',
    'description' => '子栏目13子栏目13',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=24&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1531743065',
    'updatetime' => '1531743074',
    'hitsid' => 'c-1-80',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  81 => 
  array (
    'id' => '81',
    'catid' => '24',
    'typeid' => '0',
    'title' => '子栏目14',
    'style' => '',
    'thumb' => '',
    'keywords' => '栏目',
    'description' => '子栏目14子栏目14子栏目14',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=24&id=81',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1531743078',
    'updatetime' => '1531743088',
    'hitsid' => 'c-1-81',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  82 => 
  array (
    'id' => '82',
    'catid' => '24',
    'typeid' => '0',
    'title' => '子栏目15',
    'style' => '',
    'thumb' => '',
    'keywords' => '栏目',
    'description' => '子栏目15子栏目15',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=24&id=82',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1531743091',
    'updatetime' => '1531743102',
    'hitsid' => 'c-1-82',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>