<?php
return array (
  77 => 
  array (
    'id' => '77',
    'catid' => '27',
    'typeid' => '0',
    'title' => '在杭州吃掉春天的三种方式',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0706/20180706044035435.jpg',
    'keywords' => '',
    'description' => '只有一位杭州本地的朋友除外。这位朋友对金沙厅有浓重的心理阴影。有一段时间里，她频繁地被安排相亲，几乎每次都会被安排在这里。所以一提   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=27&id=77',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530866374',
    'updatetime' => '1530866442',
    'hitsid' => 'c-1-77',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  78 => 
  array (
    'id' => '78',
    'catid' => '28',
    'typeid' => '0',
    'title' => '道油焖笋',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0706/20180706044115899.jpg',
    'keywords' => '',
    'description' => '这一道油焖笋，卖168元。贵吗？当然不便宜。可是你去其他普通小餐厅，却又难得吃到这样的味道。这一盘笋里，每一片的嫩度都几乎一样，只这   ',
    'posids' => '1',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=28&id=78',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1530866448',
    'updatetime' => '1530866483',
    'hitsid' => 'c-1-78',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>