<?php
return array (
  9 => 
  array (
    'id' => '9',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业党工团1',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042317587.jpg',
    'keywords' => '企业',
    'description' => '企业党工团1企业党工团1',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=13&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529742171',
    'updatetime' => '1529742202',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业党工团2企业党工团2',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042341221.jpg',
    'keywords' => '企业',
    'description' => '企业党工团2企业党工团2企业党工团2企业党工团2企业党工团2企业党工团2',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=13&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529742204',
    'updatetime' => '1529742225',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>