<?php
return array (
  20 => 
  array (
    'id' => '20',
    'catid' => '18',
    'typeid' => '0',
    'title' => '取用有度，满足百姓更美好生活需要',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '顶部热点2顶部热点2顶部热点2',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=18&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529746087',
    'updatetime' => '1529917589',
    'hitsid' => 'c-1-20',
    'views' => '8',
    'yesterdayviews' => '0',
    'dayviews' => '8',
    'weekviews' => '8',
    'monthviews' => '8',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '18',
    'typeid' => '0',
    'title' => '收支之间，彰显新时代政府理财之道',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '顶部热点4顶部热点4顶部热点4顶部热点4',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=18&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529746118',
    'updatetime' => '1529917346',
    'hitsid' => 'c-1-22',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '18',
    'typeid' => '0',
    'title' => '习近平到山东代表团参加审议',
    'style' => '',
    'thumb' => '',
    'keywords' => '顶部 热点',
    'description' => '顶部热点5顶部热点5顶部热点5顶部热点5',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=18&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529746136',
    'updatetime' => '1530685984',
    'hitsid' => 'c-1-23',
    'views' => '5',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '18',
    'typeid' => '0',
    'title' => '顶部热点1',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623052756228.jpg',
    'keywords' => '顶部 热点',
    'description' => '顶部热点1顶部热点1顶部热点1顶部热点1',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=18&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529746055',
    'updatetime' => '1529746082',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '18',
    'typeid' => '0',
    'title' => '增减并举，为高质量发展保驾护航',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '顶部热点3顶部热点3顶部热点3顶部热点3',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=18&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529746101',
    'updatetime' => '1529746115',
    'hitsid' => 'c-1-21',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>