<?php
return array (
  6 => 
  array (
    'id' => '6',
    'catid' => '11',
    'typeid' => '0',
    'title' => '质量安全22质量安全质量安全质量安全质量安全2',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042147702.jpg',
    'keywords' => '质量安全',
    'description' => '质量安全22质量安全质量安全质量安全质量安全2',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529742081',
    'updatetime' => '1530065223',
    'hitsid' => 'c-1-6',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  46 => 
  array (
    'id' => '46',
    'catid' => '11',
    'typeid' => '0',
    'title' => '一级审核',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '一级审核一级审核',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=46',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'member2',
    'inputtime' => '1530067936',
    'updatetime' => '1530067979',
    'hitsid' => 'c-1-46',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '11',
    'typeid' => '0',
    'title' => '质量安全1质量安全1质量安全1质量安全1质量安全1',
    'style' => '',
    'thumb' => 'http://localhost/construction/uploadfile/2018/0623/20180623042113147.jpg',
    'keywords' => '质量安全',
    'description' => '质量安全1质量安全1质量安全1质量安全1质量安全1质量安全1质量安全1质量安全1质量安全1质量安全1',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529742054',
    'updatetime' => '1529742078',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  24 => 
  array (
    'id' => '24',
    'catid' => '11',
    'typeid' => '0',
    'title' => '质量安全4质量安全4',
    'style' => '',
    'thumb' => '',
    'keywords' => '质量安全',
    'description' => '质量安全4质量安全4质量安全4质量安全4',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529751166',
    'updatetime' => '1529751188',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '11',
    'typeid' => '0',
    'title' => '质量安全5质量安全5',
    'style' => '',
    'thumb' => '',
    'keywords' => '质量安全',
    'description' => '质量安全5质量安全5质量安全5质量安全5质量安全5质量安全5',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529751191',
    'updatetime' => '1529751204',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  26 => 
  array (
    'id' => '26',
    'catid' => '11',
    'typeid' => '0',
    'title' => '质量安全6质量安全6',
    'style' => '',
    'thumb' => '',
    'keywords' => '质量安全',
    'description' => '质量安全6质量安全6质量安全6质量安全6质量安全6质量安全6',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=26',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1529751207',
    'updatetime' => '1529751225',
    'hitsid' => 'c-1-26',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  44 => 
  array (
    'id' => '44',
    'catid' => '11',
    'typeid' => '0',
    'title' => '投稿测试',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '投稿测试',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=44',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'member2',
    'inputtime' => '1530065163',
    'updatetime' => '1530065163',
    'hitsid' => 'c-1-44',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  45 => 
  array (
    'id' => '45',
    'catid' => '11',
    'typeid' => '0',
    'title' => '审核测试',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '审核测试',
    'posids' => '0',
    'url' => 'http://localhost/construction/index.php?m=content&c=index&a=show&catid=11&id=45',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'member2',
    'inputtime' => '1530067848',
    'updatetime' => '1530067848',
    'hitsid' => 'c-1-45',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>